src/game/Chat/ChatHandler.cpp

This PR passes the language of chat messages to the HandleCommand method for specific bot filtering where needed.
- None
- None
- None

Pass language to HandleCommand for adding filtering

---

src/game/AI/ScriptDevAI/scripts/custom/transmog_scripts.cpp
src/game/Maps/MapManager.cpp

Linux compile

---

src/game/AI/ScriptDevAI/scripts/custom/transmog_scripts.cpp
src/game/Chat/ChatHandler.cpp
src/game/Maps/MapManager.cpp

Addon filter fix

---

src/game/Hardcore/HardcoreMgr.cpp

Fix hardcore module crash when bot gets killed by a creature

Fix hardcore module crash when bot gets killed by a creature

---

src/game/Spells/Spell.cpp

Add bot spell immune config params
- None
- None
- None

Add bot spell immune config params

---

src/game/MotionGenerators/TargetedMovementGenerator.cpp

-Follow fix: Bots no longer match speed while following without boost.

---

src/game/MotionGenerators/PathMovementGenerator.h

Fix compilation
- None
- None
- None

Fix compilation

---

src/game/Spells/Spell.cpp

Fix immune bot spell config

---

src/game/Hardcore/HardcoreMgr.cpp

Fix for hardcore loot

---

src/game/Achievements/AchievementMgr.cpp
src/game/Achievements/AchievementMgr.h
src/game/Chat/Chat.cpp
src/game/Chat/Chat.h
src/game/Chat/Level0.cpp

Add add and remove achievement commands

---

src/game/Entities/QueryHandler.cpp

Fix books not opening the page windos

---

src/game/Loot/LootMgr.cpp

Fix double loot issue

---

src/game/Entities/Player.cpp

Fix achievement death count

---

src/game/Hardcore/HardcoreMgr.cpp

Fix hardcore module active on battlegrounds and add ignore drop loot

---

src/game/Entities/Player.cpp
src/game/Hardcore/HardcoreMgr.cpp

Fix hardcore mgr crash

---

src/game/Hardcore/HardcoreMgr.cpp

Fix linux compile error

---

src/game/Tools/PlayerDump.cpp

Include achievements to character pdump

---

src/game/Achievements/AchievementMgr.cpp

Fix linux warning

---

src/game/Hardcore/HardcoreMgr.cpp

Fix generating grave messages out of bounds

---

src/game/Hardcore/HardcoreMgr.cpp

Fix null killer for hardcore manager

---

src/game/Entities/CharacterHandler.cpp
src/game/World/World.cpp
src/game/World/World.h
src/shared/Database/SqlOperations.cpp
src/shared/Database/SqlOperations.h

Add login optimization for slow speed drives

---

src/game/Entities/Item.cpp

Remove undeeded db updates

---

src/game/Achievements/AchievementMgr.cpp

-Fix minor memory leaks in Achievement system.

---

src/game/Entities/Item.cpp

Prevent unneeded db updates of item_instance on player login.
